DROP DATABASE tpch;
CREATE DATABASE tpch;

USE tpch;

CREATE TABLE PART (
    P_PARTKEY INT, /* SF*200,000 are populated */
    P_NAME VARCHAR(55),
    P_MFGR CHAR(25),
    P_BRAND CHAR(10),
    P_TYPE VARCHAR(25),
    P_SIZE INT,
    P_CONTAINER CHAR(10),
    P_RETAILPRICE DECIMAL,
    P_COMMENT VARCHAR(23),
    PRIMARY KEY (P_PARTKEY)
);

CREATE TABLE REGION (
    R_REGIONKEY INT,
    R_NAME CHAR(25),
    R_COMMENT CHAR(152),
    PRIMARY KEY (R_REGIONKEY)
);

CREATE TABLE NATION (
    N_NATIONKEY INT, /* 25 nations are populated */
    N_NAME CHAR(25),
    N_REGIONKEY INT, /* Foreign Key to R_REGIONKEY */
    N_COMMENT VARCHAR(152),
    PRIMARY KEY (N_NATIONKEY),
    FOREIGN KEY (N_REGIONKEY) REFERENCES REGION(R_REGIONKEY)
);

CREATE TABLE SUPPLIER (
    S_SUPPKEY INT, /* SF*10,000 are populated */
    S_NAME CHAR(25),
    S_ADDRESS VARCHAR(40),
    S_NATIONKEY INT, /* Foreign key to N_NATIONKEY */
    S_PHONE CHAR(15),
    S_ACCTBAL DECIMAL,
    S_COMMENT VARCHAR(101),
    PRIMARY KEY (S_SUPPKEY),
    FOREIGN KEY (S_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
);

CREATE TABLE PARTSUPP (
    PS_PARTKEY INT, /* Foreign key to P_PARTKEY */
    PS_SUPPKEY INT, /* Foreign key to S_SUPPKEY */
    PS_AVAILQTY INT,
    PS_SUPPLYCOST DECIMAL,
    PS_COMMENT VARCHAR(199),
    PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY),
    FOREIGN KEY (PS_PARTKEY) REFERENCES PART(P_PARTKEY),
    FOREIGN KEY (PS_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY)
 ); 

CREATE TABLE CUSTOMER (
    C_CUSTKEY INT, /* SF*150,000 are populated */
    C_NAME VARCHAR(25),
    C_ADDRESS VARCHAR(40),
    C_NATIONKEY INT, /* Foreign Key to N_NATIONKEY */
    C_PHONE CHAR(15),
    C_ACCTBAL DECIMAL,
    C_MKTSEGMENT CHAR(10),
    C_COMMENT VARCHAR(117),
    PRIMARY KEY (C_CUSTKEY),
    FOREIGN KEY (C_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
);

CREATE TABLE ORDERS (
    O_ORDERKEY INT, /*SF*1,500,000 are sparsely populated */
    O_CUSTKEY INT, /* Foreign Key to C_CUSTKEY */
    O_ORDERSTATUS CHAR(1),
    O_TOTALPRICE DECIMAL,
    O_ORDERDATE DATE,
    O_ORDERPRIORITY CHAR(15),
    O_CLERK CHAR(15),
    O_SHIPPRIORITY INT,
    O_COMMENT VARCHAR(79),
    PRIMARY KEY (O_ORDERKEY),
    FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER(C_CUSTKEY)
);

CREATE TABLE LINEITEM (
    L_ORDERKEY INT, /* Foreign Key to O_ORDERKEY */
    L_PARTKEY INT, /* Foreign key to P_PARTKEY, first part of the
                      compound Foreign Key to (PS_PARTKEY,
                      PS_SUPPKEY) with L_SUPPKEY */
    L_SUPPKEY INT, /* Foreign key to S_SUPPKEY, second part of the
                      compound Foreign Key to (PS_PARTKEY, PS_SUPPKEY) with L_PARTKEY */
    L_LINENUMBER INT,
    L_QUANTITY DECIMAL,
    L_EXTENDEDPRICE DECIMAL,
    L_DISCOUNT DECIMAL,
    L_TAX DECIMAL,
    L_RETURNFLAG CHAR(1),
    L_LINESTATUS CHAR(1),
    L_SHIPDATE DATE,
    L_COMMITDATE DATE,
    L_RECEIPTDATE DATE,
    L_SHIPINSTRUCT CHAR(25),
    L_SHIPMODE CHAR(10),
    L_COMMENT VARCHAR(44),
    PRIMARY KEY(L_ORDERKEY, L_LINENUMBER),
    FOREIGN KEY (L_ORDERKEY) REFERENCES ORDERS(O_ORDERKEY),
    FOREIGN KEY (L_PARTKEY) REFERENCES PART(P_PARTKEY),
    FOREIGN KEY (L_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY)
);

